<!DOCTYPE html>
    <lang="PT-BR">
        <head>
            <meta charset="UTF-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Document</title>
        </head>
<body>
    <FORM action="index.php" method="POST">
        <P>
            Insira seu nome:
                <input type="text" name="username">
            <br>
                <hr>
            <br>
            Insira seu email:
                <input type="text" name="email">
            <br>
                <hr>
            <br>
            Insira sua senha:
                <input type="text" name="password">
            <br>
                <hr>
            <br>
            <input type="submit" value="logar">
            <br>
                <hr>
            <br>
        </P>
    </FORM>
</body>
</html>